TEMPLATEROOT = ..

CFLAGS  = -g -DUSE_STDPERIPH_DRIVER -DUSE_FULL_ASSERT
ASFLAGS = -g
# LDFLAGS = -lgcc -lc

# object files

OBJS = $(STARTUP) $(PERIPH) $(DISCOVERY) main.o loop.o sine.o

# include common make file

include $(TEMPLATEROOT)/Makefile.f3
