TEMPLATEROOT = ../..

CFLAGS  = -g
ASFLAGS = -g
# LDFLAGS = -lgcc -lc

# object files
OBJS = $(STARTUP) $(PERIPH) $(DISCOVERY) $(SYSCALLS) MersenneTwister.o main.o setup.o mtwist.o

# include common make file
include $(TEMPLATEROOT)/Makefile.f0
