TEMPLATEROOT = ../..

# compilation flags
CFLAGS  = -g
ASFLAGS = -g 

# object files
OBJS=  $(STARTUP) $(DISCOVERY) $(PERIPH) $(SYSCALLS) main.o 

# include common make file
include $(TEMPLATEROOT)/Makefile.f3
